version: '3.4'

services:
  eshopwebmvc:
    image: ${DOCKER_REGISTRY-}eshopwebmvc
    build:
      context: .
      dockerfile: src/Web/Dockerfile

      
  eshoppublicapi:
    image: ${DOCKER_REGISTRY-}eshoppublicapi
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile

      
  productcatalogms:
    image: ${DOCKER_REGISTRY-}productcatalogms
    build:
      context: ../ProductCatalogMS  
      dockerfile: Dockerfile        
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=ProductCatalog;User Id=sa;Password=@someThingComplicated1234;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - productcatalog_keys:/root/.aspnet/DataProtection-Keys
      
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=@someThingComplicated1234
      - ACCEPT_EULA=Y

volumes:
  productcatalog_keys: